### ISSUE TITLE
Run evaluate error (AssertionError)

### ISSUE THREAD

**Issue by linever** [wayveai/mile#3]
When I running evaluate.sh, i meet assertion error. The errors are follows. Please help me, very thank you!

—— —— —— >
An error occurred during Hydra's exception formatting:
AssertionError()
Traceback (most recent call last):
  File "/home/lwd/programs/anaconda3/envs/mile/lib/python3.8/site-packages/hydra/_internal/utils.py", line 252, in run_and_report
    assert mdl is not None
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "evaluate.py", line 246, in <module>
    main()
  File "/home/lwd/programs/anaconda3/envs/mile/lib/python3.8/site-packages/hydra/main.py", line 48, in decorated_main
    _run_hydra(
  File "/home/lwd/programs/anaconda3/envs/mile/lib/python3.8/site-packages/hydra/_internal/utils.py", line 377, in _run_hydra
    run_and_report(
  File "/home/lwd/programs/anaconda3/envs/mile/lib/python3.8/site-packages/hydra/_internal/utils.py", line 294, in run_and_report
    raise ex
  File "/home/lwd/programs/anaconda3/envs/mile/lib/python3.8/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/home/lwd/programs/anaconda3/envs/mile/lib/python3.8/site-packages/hydra/_internal/utils.py", line 378, in <lambda>
    lambda: hydra.run(
  File "/home/lwd/programs/anaconda3/envs/mile/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 111, in run
    _ = ret.return_value
  File "/home/lwd/programs/anaconda3/envs/mile/lib/python3.8/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "/home/lwd/programs/anaconda3/envs/mile/lib/python3.8/site-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "evaluate.py", line 171, in main
    list_render, ep_stat_dict, ep_event_dict, timestamp = run_single(
  File "evaluate.py", line 35, in run_single
    obs = env.reset()
  File "/home/lwd/codes/mile/carla_gym/carla_multi_agent_env.py", line 78, in reset
    ev_spawn_locations = self._ev_handler.reset(self._task['ego_vehicles'])
  File "/home/lwd/codes/mile/carla_gym/core/task_actor/ego_vehicle/ego_vehicle_handler.py", line 39, in reset
    blueprint = np.random.choice(self._world.get_blueprint_library().filter(bp_filter))
  File "mtrand.pyx", line 915, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken

**Comment by linever** [comment]
Thank you very much! 
The bash command is -> bash run/evaluate.sh  ~/carla_0913/CarlaUE4.sh /home/lwd/codes/mile/checkpoints/mile.ckpt 2000
My server can not connect to web, so i choose wandb 3 while running.

**Comment by anthonyhu** [comment]
Are you using CARLA 0.9.13? This code has only been tested on CARLA 0.9.11. Could you retry by downloading [CARLA 0.9.11](https://github.com/carla-simulator/carla/releases/tag/0.9.11) ?

**Comment by linever** [comment]
The advice may help me. I will try it.
Thank you again!
